version: "2"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
      - "18080:80"
  php:
    build: ./server
    volumes:
      - ./server:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=scheduler
      - DB_USERNAME=postgres
      - DB_PASSWORD=changeme
    depends_on:
      - nginx
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=scheduler
