version: "2"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
      - "18080:80"
  php:
    build: ./server
    volumes:
      - ./server:/var/www/html
    ports:
      - "9000:9000"
  db:
    image: postgres:alpine
